stages:
  - delivery

push-github:
  stage: delivery
  only:
    - main
    - latest
    - tags
  except:
    - /^flow-.*\/v.*$/
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$GITHUB_SSH_SECRET" | tr -d '\r' | ssh-add -
    - git config --local user.name "$GITHUB_USER"
    - git config --local user.email "$GITHUB_EMAIL"
    - git remote add github "$GITHUB_REMOTE_URL" || true
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME -r
    - git push github $CI_COMMIT_REF_NAME -f --tags
