# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-frontend
  namespace: flow
  labels:
    app: flow-frontend
spec:
  selector:
    matchLabels:
      app: flow-frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flow-frontend
    spec:
      containers:
        - name: flow-frontend
          image: registry.tingtt.jp/flow/frontend:v0.2.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 4000Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 270
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 270
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: NEXT_PUBLIC_API_URL
                  optional: true
          ports:
            - containerPort: 3000
              name: flow-frontend
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: flow-frontend
  namespace: flow
spec:
  selector:
    app: flow-frontend
  type: ClusterIP
  ports:
    - name: flow-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
---

