# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-mock
  namespace: flow
  labels:
    app: flow-mock
spec:
  selector:
    matchLabels:
      app: flow-mock
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flow-mock
    spec:
      containers:
        - name: flow-mock
          image: registry.tingtt.jp/flow/flow-mock:v1.0.1-588
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 1323
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: 1323
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: flow-jwt
                  key: JWT_ISSUER
                  optional: false
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flow-jwt
                  key: JWT_SECRET
                  optional: false
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: flow-mysql
                  key: MYSQL_DATABASE
                  optional: false
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: flow-mysql
                  key: MYSQL_USER
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flow-mysql
                  key: MYSQL_PASSWORD
                  optional: false
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: flow-mysql
                  key: MYSQL_HOST
                  optional: false
            - name: SERVICE_URL_PROJECTS
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_PROJECTS
                  optional: false
            - name: SERVICE_URL_SPRINTS
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_SPRINTS
                  optional: true
            - name: SERVICE_URL_TODOS
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_TODOS
                  optional: false
            - name: SERVICE_URL_POMODORO
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_POMODORO
                  optional: false
            - name: SERVICE_URL_RECORDS
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_RECORDS
                  optional: false
            - name: SERVICE_URL_DOCUMENTS
              valueFrom:
                secretKeyRef:
                  name: flow-service-url
                  key: SERVICE_URL_DOCUMENTS
                  optional: false
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: flow-env
                  key: LOG_LEVEL
                  optional: true
            - name: GZIP_LEVEL
              valueFrom:
                secretKeyRef:
                  name: flow-env
                  key: GZIP_LEVEL
                  optional: true
          ports:
            - containerPort: 1323
              name: flow-mock
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: flow-mock
  namespace: flow
spec:
  selector:
    app: flow-mock
  type: ClusterIP
  ports:
    - name: flow-mock
      protocol: TCP
      port: 1323
      targetPort: 1323
---

